# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Riyadh

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: SilentStrike Blog # the main title

tagline: Red Teaming, Weaponization, & Evasion Experts. We specialize in stealth operations, custom cybersecurity tools, and advanced phishing strategies

description: >- # used by SEO meta and the atom feed
  SilentStrike specializes in red teaming, stealth operations, and detection engineering, offering advanced cybersecurity tools and training.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://blog.silentstrike.io"

github:
  username: silentstrikelab # GitHub username

twitter:
  username: silentstrikelab # Twitter username

social:
  # Author's name for copyright and posts
  name: SilentStrike
  email: silentstrike@silentstrike.io # email address
  links:
    - https://twitter.com/silentstrikelab # Twitter link
    - https://github.com/silentstrikelab # GitHub link

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
theme_mode: dark

# The CDN endpoint for media resources.
cdn: "https://blog.silentstrike.io"

# Avatar for the sidebar
avatar: "/commons/avatar.png"

# Site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image: 

# TOC in posts.
toc: true

comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname: # fill with the Disqus shortname
  utterances:
    repo: # <gh-username>/<repo>
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    env: # [development | production]

pwa:
  enabled: true # PWA feature
  cache:
    enabled: true # PWA offline cache
    deny_paths:
      # - "/example"

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ Do not modify below unless necessary ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
